name="byzantini-website"
compatibility_date = "2024-03-09"
compatibility_flags = [ "nodejs_compat" ]

# Pages-specific configuration
pages_build_output_dir = "./dist"

#!!!!! Uploaded files to bucket are stored locally
[[r2_buckets]]
binding = "S3_BUCKET"
bucket_name = "byzantini-bucket"
preview_bucket_name = "bucket-dev"
